import { Tournament, Match, Team, Player, User, PlayerRole } from '../types';

// Mock teams
export const mockTeams: Team[] = [
  {
    id: 'team1',
    name: 'Mumbai Warriors',
    captain: 'Rajesh Kumar',
    players: [
      { id: 'p1', name: 'Rajesh Kumar', jerseyNumber: 1, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p2', name: 'Amit Sharma', jerseyNumber: 2, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p3', name: 'Suresh Patil', jerseyNumber: 3, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p4', name: 'Vikram Singh', jerseyNumber: 4, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p5', name: 'Deepak Rao', jerseyNumber: 5, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p6', name: 'Arjun Desai', jerseyNumber: 6, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p7', name: 'Karan Joshi', jerseyNumber: 7, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p8', name: 'Rahul Mehta', jerseyNumber: 8, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p9', name: 'Sanjay Iyer', jerseyNumber: 9, teamId: 'team1', role: 'playing', isActive: true },
      { id: 'p10', name: 'Ankit Verma', jerseyNumber: 10, teamId: 'team1', role: 'substitute', isActive: false },
      { id: 'p11', name: 'Rohit Nair', jerseyNumber: 11, teamId: 'team1', role: 'substitute', isActive: false },
      { id: 'p12', name: 'Nikhil Shah', jerseyNumber: 12, teamId: 'team1', role: 'substitute', isActive: false },
      { id: 'p13', name: 'Sachin Gupta', jerseyNumber: 13, teamId: 'team1', role: 'substitute', isActive: false },
      { id: 'p14', name: 'Vishal Pillai', jerseyNumber: 14, teamId: 'team1', role: 'substitute', isActive: false },
      { id: 'p15', name: 'Manoj Reddy', jerseyNumber: 15, teamId: 'team1', role: 'substitute', isActive: false },
    ],
  },
  {
    id: 'team2',
    name: 'Delhi Defenders',
    captain: 'Pradeep Yadav',
    players: [
      { id: 'p16', name: 'Pradeep Yadav', jerseyNumber: 1, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p17', name: 'Ashok Kumar', jerseyNumber: 2, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p18', name: 'Naveen Chauhan', jerseyNumber: 3, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p19', name: 'Ramesh Pal', jerseyNumber: 4, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p20', name: 'Dinesh Rawat', jerseyNumber: 5, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p21', name: 'Anil Bhatt', jerseyNumber: 6, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p22', name: 'Pawan Tomar', jerseyNumber: 7, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p23', name: 'Sunil Malik', jerseyNumber: 8, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p24', name: 'Rakesh Bisht', jerseyNumber: 9, teamId: 'team2', role: 'playing', isActive: true },
      { id: 'p25', name: 'Gopal Chand', jerseyNumber: 10, teamId: 'team2', role: 'substitute', isActive: false },
      { id: 'p26', name: 'Yogesh Negi', jerseyNumber: 11, teamId: 'team2', role: 'substitute', isActive: false },
      { id: 'p27', name: 'Manish Sharma', jerseyNumber: 12, teamId: 'team2', role: 'substitute', isActive: false },
      { id: 'p28', name: 'Harish Thakur', jerseyNumber: 13, teamId: 'team2', role: 'substitute', isActive: false },
      { id: 'p29', name: 'Vijay Singh', jerseyNumber: 14, teamId: 'team2', role: 'substitute', isActive: false },
      { id: 'p30', name: 'Ajay Rathore', jerseyNumber: 15, teamId: 'team2', role: 'substitute', isActive: false },
    ],
  },
  {
    id: 'team3',
    name: 'Chennai Challengers',
    captain: 'Murugan S',
    players: Array.from({ length: 15 }, (_, i) => ({
      id: `p${31 + i}`,
      name: `Player ${i + 1}`,
      jerseyNumber: i + 1,
      teamId: 'team3',
      role: (i < 9 ? 'playing' : 'substitute') as PlayerRole,
      isActive: i < 9,
    })),
  },
  {
    id: 'team4',
    name: 'Pune Panthers',
    captain: 'Ganesh Pawar',
    players: Array.from({ length: 15 }, (_, i) => ({
      id: `p${46 + i}`,
      name: `Player ${i + 1}`,
      jerseyNumber: i + 1,
      teamId: 'team4',
      role: (i < 9 ? 'playing' : 'substitute') as PlayerRole,
      isActive: i < 9,
    })),
  },
];

// Mock tournaments
export const mockTournaments: Tournament[] = [
  {
    id: 't1',
    name: 'National Kho-Kho Championship 2025',
    startDate: '2025-10-15',
    endDate: '2025-10-25',
    location: 'Mumbai, Maharashtra',
    type: 'National',
    status: 'ongoing',
  },
  {
    id: 't2',
    name: 'State Level Tournament',
    startDate: '2025-11-01',
    endDate: '2025-11-10',
    location: 'Pune, Maharashtra',
    type: 'State',
    status: 'upcoming',
  },
  {
    id: 't3',
    name: 'Inter-District Championship',
    startDate: '2025-09-20',
    endDate: '2025-09-28',
    location: 'Delhi',
    type: 'District',
    status: 'completed',
  },
];

// Mock matches
export const mockMatches: Match[] = [
  {
    id: 'm1',
    matchNumber: 'M001',
    tournamentId: 't1',
    tournamentName: 'National Kho-Kho Championship 2025',
    teamA: mockTeams[0],
    teamB: mockTeams[1],
    dateTime: '2025-10-08T14:00:00',
    venue: 'Stadium A',
    status: 'live',
    scorerId: 's1',
    scorerName: 'John Scorer',
    scoreA: 15,
    scoreB: 12,
    innings: 4,
    turnDuration: 540, // 9 minutes
  },
  {
    id: 'm2',
    matchNumber: 'M002',
    tournamentId: 't1',
    tournamentName: 'National Kho-Kho Championship 2025',
    teamA: mockTeams[2],
    teamB: mockTeams[3],
    dateTime: '2025-10-08T16:30:00',
    venue: 'Stadium B',
    status: 'upcoming',
    scorerId: 's1',
    scorerName: 'John Scorer',
    innings: 4,
    turnDuration: 540,
  },
  {
    id: 'm3',
    matchNumber: 'M003',
    tournamentId: 't1',
    tournamentName: 'National Kho-Kho Championship 2025',
    teamA: mockTeams[0],
    teamB: mockTeams[2],
    dateTime: '2025-10-09T14:00:00',
    venue: 'Stadium A',
    status: 'upcoming',
    scorerId: 's1',
    scorerName: 'John Scorer',
    innings: 4,
    turnDuration: 540,
  },
  {
    id: 'm4',
    matchNumber: 'M004',
    tournamentId: 't1',
    tournamentName: 'National Kho-Kho Championship 2025',
    teamA: mockTeams[1],
    teamB: mockTeams[3],
    dateTime: '2025-10-07T14:00:00',
    venue: 'Stadium C',
    status: 'finished',
    scorerId: 's1',
    scorerName: 'John Scorer',
    scoreA: 28,
    scoreB: 19,
    innings: 4,
    turnDuration: 540,
  },
];

// Mock users
export const mockUsers: User[] = [
  {
    id: 'admin1',
    name: 'Admin User',
    email: 'admin@kho-kho.com',
    role: 'admin',
  },
  {
    id: 's1',
    name: 'John Scorer',
    email: 'scorer@kho-kho.com',
    role: 'scorer',
  },
];
